/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE, modified by Abe Jordan
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * This file is modified to include the CMSIS device header
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f3xx.h"

int main(void)
{
    /* Loop forever */
	while (1);
}
